# Generated by Django 4.1.3 on 2023-01-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_QT',
            field=models.BooleanField(default=False),
        ),
    ]
